pg93:
  ports:
    - "54323:5432"
  image: postgres:9.3
  env_file: .env

pg94:
  ports:
    - "54324:5432"
  image: postgres:9.4
  env_file: .env

mysql55:
  ports:
    - "33055:3306"
  image: mysql:5.5
  env_file: .env

mysql56:
  ports:
    - "33056:3306"
  image: mysql:5.6
  env_file: .env
   
#mysql51:
#  ports:
#    - "33051:3306"
#  image: github.com/ignatov/docker-mysql-5.1
#  env_file: .env

