pg84:
  ports:
    - "54314:5432"
  image: postgres:8.4
  env_file: .env

pg90:
  ports:
    - "54320:5432"
  image: postgres:9.0
  env_file: .env

pg91:
  ports:
    - "54321:5432"
  image: postgres:9.1
  env_file: .env

pg92:
  ports:
    - "54322:5432"
  image: postgres:9.2
  env_file: .env

pg93:
  ports:
    - "54323:5432"
  image: postgres:9.3
  env_file: .env

pg94:
  ports:
    - "54324:5432"
  image: postgres:9.4
  env_file: .env

mysql55:
  ports:
    - "33055:3306"
  image: mysql:5.5
  env_file: .env

mysql56:
  ports:
    - "33056:3306"
  image: mysql:5.6
  env_file: .env
   
mysql51:
  ports:
    - "33051:3306"
  image: ignatov/docker-mysql-5.1
  env_file: .env

# oracle VM options
# -Duser.country=en -Duser.language=en
# todo: use debian:wheezy
# todo: reduce size as https://github.com/MaksymBilenko/docker-oracle-xe-11g does
oracle11:
  ports:
    - "1521:1521"
  image: kazunobufujii/oracle-xe-11g
  env_file: .env